curriculum/urls.py
from django.urls import path
from curriculum import views

urlpatterns = [
    path('', views.home, name='home'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path('', include('curriculum.urls')),
]

curriculum/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Experience(models.Model):
    company = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    description = RichTextField()

    def __str__(self):
        return self.company


class Education(models.Model):
    school = models.CharField(max_length=100)
    degree = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    description = RichTextField()

    def __str__(self):
        return self.school


class Skill(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

curriculum/views.py
from django.shortcuts import render
from curriculum.models import Experience, Education, Skill, Category


def home(request):
    all_experiences = Experience.objects.order_by("-id")
    all_educations = Education.objects.order_by("-id")
    all_categories = Category.objects.all()
    all_skills = Skill.objects.all()
    context = {
        'all_experiences': all_experiences,
        'all_educations': all_educations,
        'all_categories': all_categories,
        'all_skills': all_skills,
    }

    return render(request, 'base.html', context)

curriculum/templates/contact.html
{% load static %}


<div class="container">
    <div class="row" >
        <div class="col-lg-2 col-sm-6 col-12 mb-3 align-self-center">
            <a rel='nofollow' href='https://www.linkedin.com/in/adrianhelerea' target="_blank">
                <img class="img-fluid img-thumbnail" src='static/img/linkedinQR_static.png' alt='linkedin'>
            </a>
        </div>
        <div class="col-lg-2 col-sm-6 col-12 mb-3 align-self-center">
            <a rel='nofollow' href='https://github.com/hellyworld/RESUME' target="_blank">
                <img class="img-fluid img-thumbnail" src='static/img/githubQR_static.png' alt='sololearn'>
            </a>
        </div>
        <div class="col-lg-8 col-12 align-self-center">
            <div class="form-row disabled">
                <div class="col-xl-4 col-lg-5 col-4">
                    <div class="form-group">
                        <label class="text-primary" for="senderName2">Name</label>
                        <input type="text" id="senderName2" placeholder="Your name here" required disabled>
                    </div>
                    <div class="form-group">
                        <label class="text-primary" for="senderEmail2">E-mail</label>
                        <input type="text" id="senderEmail2" placeholder="Your e-mail here" required disabled>
                    </div>
                </div>
                <div class="col-xl-8 col-lg-7 col-xs-12">
                    <div class="form-group">
                        <label class="text-primary" for="messageText2">Message</label>
                        <textarea class="form-control" name="messageText" id="messageText2" placeholder="Your message here" cols="30" rows="2" disabled></textarea>
                    </div>
                    <button class="btn btn-primary btn-block btn-sm" type="submit" disabled>Send</button>
                </div>
            </div>
        </div>
    </div>
</div>

curriculum/templates/curriculum/admin/change_form.html
{% extends "admin/change_form.html" %}

{% load wysiwyg %}

{% block extrahead %}

	{{ block.super }}

	{% wysiwyg_setup %}

{% endblock %}

{% block extrastyle %}

	{{ block.super }}

	<style type="text/css">
		<!--

			{% comment %}`

				The below CSS rules are here to fix admin layout issues using
				CKEditor v3.6.1, or YUI Editor, via Django 1.3.

				Note: "kama" is the skin name; you will need to change this if
				using a different skin.

				CSS tested with:

				Mac OSX v10.6.7
				Chrome v12.0.742.100; Firefox v5.0; Safari v5.0.5; Opera v11.11

				Windows Vista
				Chrome v11.11; Internet Explorer v9.0.8112.16421;
				Internet Explorer v8.0.6001.19019; Opera v11.11; Safari v5.0.5;
				Firefox v3.6.11; Flock v3.5.3.4641

				Windows XP
				Internet Explorer v6.0.2900.5512...

			{% endcomment %}

			/* CKEditor: */
			.cke_skin_kama {
				/* Un-comment one line or the other: */
				/*width: 85%; float: left; display: inline;*/
				/*clear: left;*/
			}

			/* YUI Editor: */
			.yui-editor-container {
				/* IBID: */
				/*float: left; display: inline;*/
				/*clear: left;*/
			}

		-->
	</style>

{% endblock %}
{% block content %}

	{{ block.super }}

	{# Replace XXXXXXXX with field name: #}
	{% wysiwyg_editor "id_description" %}

	{% comment %}
		{# ckeditor custom config example #}
		{% wysiwyg_editor "id_XXXXXXXX" "id_XXXXXXXX_editor" "{ toolbar: 'compact_toolbar' }" %}
	{% endcomment %}

	{# ... add more here... #}
{% endblock %}

curriculum/templates/education.html
{% load static %}


{% if all_educations %}
    {% for education in all_educations %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>{{ education.school }}</h3>
                <h6>{{ education.degree }}</h6>
            </div>
            <div class="col-md-4">
                <h6 class="text-sm-left text-md-right text-muted">{{ education.location }}</h6>
                <h6 class="text-sm-left text-md-right text-muted">{{ education.start_date|date:'M Y'}} -
                    {% if education.end_date is null %}
                        Present
                    {% else %}
                        {{ education.end_date|date:'M Y'}}
                    {% endif %}
                </h6>
            </div>
        </div>
        <a data-toggle="collapse" href="#multi_collapse_education_{{ education.id }}">
            <i class="far fa-caret-square-down"></i>
            Details
        </a>
        <div class="container collapse multi-collapse" id="multi_collapse_education_{{ education.id }}">
            {{ education.description | safe }}
        </div>
    </div>
    <br>
    {% endfor %}
{% else %}
    <h2>You don't have any education, so please go back to school!</h2>
{% endif %}

curriculum/templates/experience.html
{% load static %}


{% if all_experiences %}
    {% for experience in all_experiences %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>{{ experience.company }}</h3>
                <h6>{{ experience.position }}</h6>
            </div>
            <div class="col-md-4">
                <h6 class="text-sm-left text-md-right text-muted">{{ experience.location }}</h6>
                <h6 class="text-sm-left text-md-right text-muted">{{ experience.start_date|date:'M Y'}} -
                    {% if experience.end_date is null %}
                        Present
                    {% else %}
                        {{ experience.end_date|date:'M Y'}}
                    {% endif %}
                </h6>
            </div>
        </div>
        <a data-toggle="collapse" href="#multi_collapse_experiece_{{ experience.id }}">
            <i class="far fa-caret-square-down"></i>
            Details
        </a>
        <div class="container collapse multi-collapse" id="multi_collapse_experiece_{{ experience.id }}">
            {{ experience.description | safe}}
        </div>
    </div>
    <br>
    {% endfor %}
{% else %}
    <h2>You don't have any experience, so please start your career!</h2>
{% endif %}

curriculum/templates/jumbotron.html
{% load static %}

<div class="container" id="brand">
    <div class="jumbotron text-center pt-3">
        <div class="row">
            <div class="col-lg-4 mb-3 align-self-center">
                <img src="static/img/AdrianHelerea.jpg" alt="Adrian" class="img-thumbnail">
            </div>
            <div class="col-lg-8 text-center">
                <h1>Adrian Helerea</h1>
                <blockquote>
                  <h5>“Be the change you wish to see in the world.”</h5>
                  <footer class="blockquote-footer text-right">Mahatma Gandhi</footer>
                </blockquote>

                <h4 class="text-justify"><bolt>My objective:</bolt></h4>
                <p class="text-justify">
                    I have been working in engineering for the last eight years, from Research Engineer in Silviculture
                    to Design Engineer in Storage Facilities, where I used Python to automate processes, and I am now
                    looking to fully transition as a Python Developer.
                </p>
                <p class="text-justify">
                    With strong ability of self taught and professional development, in the last year I studied and
                    worked to build web programs with Django and small scripts with Python and I am eager to improve my
                    Python skills in Computer Vision.
                </p>
            </div>
        </div>
    </div>
</div>

curriculum/templates/navbar.html
{% load static %}


<div class="container">
    <nav class="nav navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--left side of navbar-->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="nav navbar-nav pull-sm-left">
                    <li class="nav-item">
                        <a class="navbar-brand" href="#brand">
                            Adrian Helerea
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#experience">
                            <span class="fas fa-briefcase mr-2" aria-hidden="true"></span>Experience
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#education">
                            <span class="fas fa-graduation-cap mr-2" aria-hidden="true"></span>Education
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#skills">
                            <span class="fas fa-wrench mr-2" aria-hidden="true"></span>Skills
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#strength">
                            <span class="fas fa-bolt mr-2" aria-hidden="true"></span>Strengths
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">
                            <span class="fas fa-paper-plane mr-2" aria-hidden="true"></span>Contact
                        </a>
                    </li>
                </ul>
            </div>

            <!--right side of navbar-->
            <div>
                <ul class="nav pull-sm-right">
                    <li class="nav-item">
                        <a class="nav-link" href="mailto:helereaiadrian@gmail.com">
                            <span class="fas fa-envelope" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span class="fas fa-print" onclick="printPage()" aria-hidden="true"></span>
                        </a>
                    </li>
                    <!--<li class="nav-item">-->
                        <!--<a class="nav-link" href="#">-->
                            <!--<span class="fas fa-cloud-download-alt" aria-hidden="true"></span>-->
                        <!--</a>-->
                    <!--</li>-->
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.linkedin.com/in/adrianhelerea" target="_blank">
                            <span class="fab fa-linkedin" aria-hidden="true"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

curriculum/templates/skills.html
{% load static %}

{% if all_skills%}
    {% for category in all_categories %}
      <div class="container text-left">

        <h3 class="">{{ category.name }}</h3>
          <div class="container">
            <div class="row">
              {% for skill in category.skill_set.all %}
              <div class="col-sm-3 mb-3">
                  <label for="html">{{ skill.name }}</label>
                <div class="progress">
                  <div class="progress-bar" id="html" role="progressbar" style="width:{{ skill.level }}%"></div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <br>
      </div>
    {% endfor %}
{% else %}
  <h2>You have no skills, so you need to level up!</h2>
{% endif %}

curriculum/templates/strengths.html
{% load static %}


<div class="container">
    <div class="container">
        <ul class="">
          <li>Very well organized, sharp and able to learn new tasks easily</li>
          <li>Adaptable and open minded, ability to prioritize and ambitious</li>
          <li>Flexible, quick to pick up new skills and eager to learn continuously</li>
          <li>Effectively manage crisis and challenging situations</li>
          <li>Resourceful and able to maintain grace under pressure </li>
          <li>Health Conscious – alcohol/drug free, non-smoker</li>
        </ul>
    </div>
</div>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>{% block head_title %}Resume Adrian Helerea{% endblock  %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/resume.css' %}">
  </head>
  <body>

      <div class="container">
          {% include "navbar.html" %}
          {% include "jumbotron.html" %}

          <div class="container">
              <div class="bpu afn afd">
                  <h2 class="bpv bpw" id="experience"><span class="fas fa-briefcase mr-2"></span>Experience</h2>
              </div>
              <div class="container">
                  {% include "experience.html" %}
              </div>
          </div>

          <div class="container">
              <div class="bpu afn afd">
                  <h2 class="bpv bpw" id="education"><span class="fas fa-graduation-cap mr-2"></span>Education</h2>
              </div>
              <div class="container">
                  {% include "education.html" %}
              </div>
          </div>

          <div class="container">
              <div class="bpu afn afd">
                  <h2 class="bpv bpw" id="skills"><span class="fas fa-wrench mr-2"></span>Skills</h2>
              </div>
              <div class="container">
                  {% include "skills.html" %}
              </div>
          </div>

          <div class="container">
              <div class="bpu afn afd">
                  <h2 class="bpv bpw" id="strength"><span class="fas fa-bolt mr-2"></span>Strengths</h2>
              </div>
              <div class="container">
                  {% include "strengths.html" %}
              </div>
          </div>

          <div class="container">
              <div class="bpu afn afd">
                  <h2 class="bpv bpw" id="contact"><span class="fas fa-paper-plane mr-2"></span>Contact</h2>
              </div>
              <div class="container">
                  {% include "contact.html" %}
              </div>
          </div>

          <div class="container text-right text-muted">
              <small>&copy; 2018 Copyrights: Adrian Helerea</small>
          </div>
      </div>
  </body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/resume.js' %}"></script>
</html>